const productData = {
  "categories": [
    {
      "name": "Combo Decor",
      "slug": "combo-decor",
      "description": "Các set decor đồng bộ theo từng không gian sống."
    },
    {
      "name": "Nến thơm",
      "slug": "nen-thom",
      "description": "Nến thơm và phụ kiện tạo hương cho phòng ngủ, phòng khách."
    },
    {
      "name": "Tranh decor",
      "slug": "tranh-decor",
      "description": "Tranh treo tường, tranh để bàn và tranh trang trí theo mùa."
    },
    {
      "name": "Đèn trang trí",
      "slug": "den-trang-tri",
      "description": "Đèn ngủ, đèn bàn và các mẫu đèn decor cho không gian sống."
    },
    {
      "name": "Tượng trang trí",
      "slug": "tuong-trang-tri",
      "description": "Tượng decor nghệ thuật cho bàn làm việc, kệ sách và phòng khách."
    },
    {
      "name": "Đồng hồ",
      "slug": "dong-ho",
      "description": "Đồng hồ để bàn và đồng hồ decor cho góc học tập, làm việc."
    },
    {
      "name": "Cốc và phụ kiện",
      "slug": "coc-va-phu-kien",
      "description": "Ly, cốc, loa mini và các phụ kiện nhỏ cho góc chill."
    },
    {
      "name": "Bình hoa",
      "slug": "binh-hoa",
      "description": "Bình hoa, lọ hoa và phụ kiện cắm hoa decor."
    },
    {
      "name": "Chậu cây",
      "slug": "chau-cay",
      "description": "Chậu cây mini và vật phẩm xanh cho góc phòng."
    },
    {
      "name": "Giá đỡ",
      "slug": "gia-do",
      "description": "Giá đỡ sách, laptop và phụ kiện sắp xếp bàn làm việc."
    }
  ],
  "products": [
    {
      "legacyCategoryId": 2,
      "categorySlug": "nen-thom",
      "slug": "rubix-candle",
      "name": "Nến thơm hình Rubix đơn giản, sang trọng",
      "price": 24000,
      "rating": 4,
      "imageFile": "rubix-candle.png",
      "imageUrl": "assets/images/products/rubix-candle.png",
      "sourceImage": "Rectangle 31.png",
      "description": "Biến góc nhỏ của bạn thành một không gian đậm chất nghệ thuật với Nến thơm hình Rubix dễ thương. Thiết kế khối cầu độc đáo cùng gam màu pastel ngọt ngào giúp sản phẩm vừa là vật dụng tạo hương thơm thư giãn vừa là món phụ kiện decor.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, bàn làm việc; Tạo góc sống ảo, góc chill tại nhà; Làm quà tặng tinh tế"
    },
    {
      "legacyCategoryId": 4,
      "categorySlug": "den-trang-tri",
      "slug": "mini-fire-lamp",
      "name": "Đèn ngủ mini hình đống lửa trại chibi dễ thương để bàn",
      "price": 39000,
      "rating": 4,
      "imageFile": "mini-fire-lamp.png",
      "imageUrl": "assets/images/products/mini-fire-lamp.png",
      "sourceImage": "Rectangle 31-12.png",
      "description": "Mang không khí ấm áp, vui tươi của những buổi cắm trại vào căn phòng với đèn ngủ mini hình đống lửa trại chibi. Ánh sáng cam ấm giúp tạo cảm giác thư giãn và dễ chịu.",
      "suitableFor": "Trang trí bàn học, bàn làm việc, tab đầu giường; Tạo điểm nhấn cho góc decor; Làm quà tặng sinh nhật"
    },
    {
      "legacyCategoryId": 3,
      "categorySlug": "tranh-decor",
      "slug": "flower-market-amsterdam",
      "name": "Tranh Treo Tường Flower Market Amsterdam Hình Hoa Tulip",
      "price": 50000,
      "rating": 4,
      "imageFile": "flower-market-amsterdam.png",
      "imageUrl": "assets/images/products/flower-market-amsterdam.png",
      "sourceImage": "Rectangle 69.png",
      "description": "Tranh treo tường Flower Market Amsterdam mang phong cách vintage hiện đại với hình ảnh hoa tulip rực rỡ và tông pastel nhẹ nhàng, giúp không gian thêm tươi mới và lãng mạn.",
      "suitableFor": "Treo tường phòng khách, phòng ngủ, góc làm việc; Decor quán cà phê, tiệm trà bánh; Làm quà tặng tân gia"
    },
    {
      "legacyCategoryId": 2,
      "categorySlug": "nen-thom",
      "slug": "gold-candle-tray",
      "name": "Khay đựng nến thơm bằng kim loại có chong chóng quay",
      "price": 80000,
      "rating": 4,
      "imageFile": "gold-candle-tray.png",
      "imageUrl": "assets/images/products/gold-candle-tray.png",
      "sourceImage": "Rectangle 31-5.png",
      "description": "Khay nến kim loại có chong chóng quay là phụ kiện decor hiện đại. Khi sử dụng cùng nến, hơi nóng giúp chong chóng chuyển động tạo hiệu ứng ánh sáng sinh động.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, bàn làm việc; Tạo góc chill tại nhà; Làm quà tặng tinh tế"
    },
    {
      "legacyCategoryId": 5,
      "categorySlug": "tuong-trang-tri",
      "slug": "minimal-statue",
      "name": "Tượng gốm sứ trang trí bàn làm việc hình người ôm đầu nghệ thuật tối giản",
      "price": 36000,
      "rating": 4,
      "imageFile": "minimal-statue.png",
      "imageUrl": "assets/images/products/minimal-statue.png",
      "sourceImage": "Rectangle 31-8.png",
      "description": "Tượng gốm sứ phong cách tối giản với dáng người ôm đầu nghệ thuật, phù hợp để tạo điểm nhấn nhẹ nhàng cho bàn làm việc, kệ sách hoặc không gian studio.",
      "suitableFor": "Trang trí bàn làm việc; Decor kệ sách, phòng khách; Làm quà tặng cho người yêu nghệ thuật"
    },
    {
      "legacyCategoryId": 7,
      "categorySlug": "coc-va-phu-kien",
      "slug": "hot-cup",
      "name": "Cốc 6 múi cuốn cuộn cực nóng",
      "price": 97000,
      "rating": 4,
      "imageFile": "hot-cup.png",
      "imageUrl": "assets/images/products/hot-cup.png",
      "sourceImage": "glass1.png",
      "description": "Cốc thiết kế 3D độc lạ mô phỏng thân hình cơ bắp, mang lại cảm giác vui nhộn và cá tính cho góc cá nhân.",
      "suitableFor": "Thưởng thức cà phê, trà, nước uống; Decor bàn làm việc; Làm quà tặng vui nhộn"
    },
    {
      "legacyCategoryId": 4,
      "categorySlug": "den-trang-tri",
      "slug": "lily-light",
      "name": "Đèn trang trí Lily of the Valley",
      "price": 279000,
      "rating": 4,
      "imageFile": "lily-light.png",
      "imageUrl": "assets/images/products/lily-light.png",
      "sourceImage": "Rectangle 31-2.png",
      "description": "Đèn trang trí Lily of the Valley mô phỏng hoa linh lan phát sáng trong vòm kính, tạo ánh sáng vàng ấm và cảm giác lãng mạn cho không gian.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, tab đầu giường; Tạo góc thư giãn; Làm quà tặng sinh nhật, kỷ niệm"
    },
    {
      "legacyCategoryId": 6,
      "categorySlug": "dong-ho",
      "slug": "led-pen-clock",
      "name": "Đồng hồ kiêm ống đựng bút LED tối giản",
      "price": 248000,
      "rating": 4,
      "imageFile": "led-pen-clock.png",
      "imageUrl": "assets/images/products/led-pen-clock.png",
      "sourceImage": "Rectangle 31-4.png",
      "description": "Đồng hồ kiêm ống đựng bút LED có thiết kế hiện đại, giúp quản lý thời gian và sắp xếp văn phòng phẩm gọn gàng.",
      "suitableFor": "Trang trí bàn học, bàn làm việc; Quản lý thời gian; Làm quà tặng công nghệ"
    },
    {
      "legacyCategoryId": 2,
      "categorySlug": "nen-thom",
      "slug": "orange-candle",
      "name": "Nến thơm hình quả quýt, mùi hương tươi mát",
      "price": 19000,
      "rating": 4,
      "imageFile": "orange-candle.png",
      "imageUrl": "assets/images/products/orange-candle.png",
      "sourceImage": "Rectangle 31-19.png",
      "description": "Nến thơm hình quả quýt có thiết kế mô phỏng chân thực, màu cam nổi bật và hương thơm tươi mát, phù hợp để decor góc phòng.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, bàn làm việc; Tạo góc chill tại nhà; Làm quà tặng tinh tế"
    },
    {
      "legacyCategoryId": 7,
      "categorySlug": "coc-va-phu-kien",
      "slug": "pearl-cup-set",
      "name": "Bộ ly sứ men ngọc trai đính nơ 3d phong cách hàn quốc kèm đĩa lót cực xinh",
      "price": 120000,
      "rating": 4,
      "imageFile": "pearl-cup-set.png",
      "imageUrl": "assets/images/products/pearl-cup-set.png",
      "sourceImage": "Rectangle 31-1.png",
      "description": "Bộ ly sứ men ngọc trai đính nơ 3D phong cách Hàn Quốc, đi kèm đĩa lót đồng bộ, phù hợp cho trà chiều và decor bàn ăn.",
      "suitableFor": "Thưởng thức trà, cà phê; Decor bàn ăn, tủ kính; Làm quà tặng sinh nhật"
    },
    {
      "legacyCategoryId": 8,
      "categorySlug": "binh-hoa",
      "slug": "white-vase",
      "name": "Bình hoa thạch cao phong cách bất đối xứng màu trắng",
      "price": 81000,
      "rating": 4,
      "imageFile": "white-vase.png",
      "imageUrl": "assets/images/products/white-vase.png",
      "sourceImage": "vase2.png",
      "description": "Bình hoa thạch cao màu trắng với thiết kế bất đối xứng, tạo vẻ hiện đại, tinh tế và thanh lịch cho không gian sống.",
      "suitableFor": "Trang trí bàn trà, bàn làm việc, kệ sách; Decor studio, quán cà phê; Làm quà tặng tân gia"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "muse-desk-set",
      "name": "Set Bàn Học Nàng Thơ",
      "price": 489000,
      "rating": 4,
      "imageFile": "muse-desk-set.png",
      "imageUrl": "assets/images/products/muse-desk-set.png",
      "sourceImage": "set10.png",
      "description": "Combo Set Bàn Học Nàng Thơ giúp biến góc học tập và làm việc thành không gian nghệ thuật nhẹ nhàng, ngọt ngào và đầy cảm hứng.",
      "suitableFor": "Trang trí góc cá nhân; Decor studio, hiệu sách, thư viện nhỏ; Làm quà tặng ý nghĩa"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "work-corner-set",
      "name": "Set góc làm việc chuyên nghiệp năng suất",
      "price": 518000,
      "rating": 4,
      "imageFile": "work-corner-set.png",
      "imageUrl": "assets/images/products/work-corner-set.png",
      "sourceImage": "set1.png",
      "description": "Set góc làm việc chuyên nghiệp giúp tối ưu không gian, kết hợp đồng hồ LED, giá đỡ laptop, tranh decor và ánh sáng dịu nhẹ.",
      "suitableFor": "Nâng cấp góc làm việc cá nhân; Decor văn phòng; Làm quà tặng cho đồng nghiệp"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "warm-guest-set",
      "name": "Set góc tiếp khách ấm cúng - lịch sự - sang trọng",
      "price": 359000,
      "rating": 4,
      "imageFile": "warm-guest-set.png",
      "imageUrl": "assets/images/products/warm-guest-set.png",
      "sourceImage": "set9.png",
      "description": "Combo góc tiếp khách ấm cúng kết hợp đồng hồ gỗ, tranh canvas, khay nến, tượng và bình hoa khô, tạo điểm nhấn sang trọng cho không gian.",
      "suitableFor": "Trang trí bàn trà phòng khách; Decor văn phòng, showroom; Làm quà tặng tân gia"
    },
    {
      "legacyCategoryId": 6,
      "categorySlug": "dong-ho",
      "slug": "flower-clock",
      "name": "Đồng hồ bông hoa xinh xắn phong cách dễ thương",
      "price": 69000,
      "rating": 4,
      "imageFile": "flower-clock.png",
      "imageUrl": "assets/images/products/flower-clock.png",
      "sourceImage": "Rectangle 31-9.png",
      "description": "Đồng hồ hình bông hoa có thiết kế dễ thương, màu sắc tươi sáng, vừa giúp theo dõi thời gian vừa là món decor sinh động.",
      "suitableFor": "Trang trí bàn học, bàn làm việc, kệ sách; Decor phòng bé; Làm quà sinh nhật"
    },
    {
      "legacyCategoryId": 6,
      "categorySlug": "dong-ho",
      "slug": "wood-clock",
      "name": "Đồng hồ phong cách tối giản, sang trọng",
      "price": 89000,
      "rating": 4,
      "imageFile": "wood-clock.png",
      "imageUrl": "assets/images/products/wood-clock.png",
      "sourceImage": "Rectangle 31-14.png",
      "description": "Đồng hồ gỗ phong cách tối giản với đường nét tự nhiên, tạo cảm giác mộc mạc, bình yên và sang trọng.",
      "suitableFor": "Trang trí bàn làm việc, bàn học, kệ sách; Decor không gian tối giản; Làm quà tặng lưu niệm"
    },
    {
      "legacyCategoryId": 8,
      "categorySlug": "binh-hoa",
      "slug": "white-stone-vase",
      "name": "Bình hoa thạch cao cao cấp phong cách tối giản",
      "price": 61000,
      "rating": 4,
      "imageFile": "white-stone-vase.png",
      "imageUrl": "assets/images/products/white-stone-vase.png",
      "sourceImage": "vase1.png",
      "description": "Bình hoa thạch cao cao cấp phong cách tối giản, thiết kế thanh lịch, phù hợp cắm hoa khô hoặc hoa nghệ thuật.",
      "suitableFor": "Trang trí bàn làm việc, kệ sách, tab đầu giường; Decor studio; Làm quà tặng tân gia"
    },
    {
      "legacyCategoryId": 3,
      "categorySlug": "tranh-decor",
      "slug": "orange-canvas",
      "name": "Tranh canvas treo tường họa tiết quả cam và hoa trắng nhỏ tối giản hiện đại",
      "price": 50000,
      "rating": 4,
      "imageFile": "orange-canvas.png",
      "imageUrl": "assets/images/products/orange-canvas.png",
      "sourceImage": "Rectangle 31-20.png",
      "description": "Tranh canvas họa tiết quả cam và hoa trắng nhỏ mang không khí Địa Trung Hải, giúp không gian thêm tươi mới và tràn đầy năng lượng.",
      "suitableFor": "Treo tường phòng khách, phòng ăn, gian bếp; Decor quán cà phê, homestay; Làm quà tặng tân gia"
    },
    {
      "legacyCategoryId": 2,
      "categorySlug": "nen-thom",
      "slug": "persimmon-candle",
      "name": "Nến thơm hình quả hồng dễ thương",
      "price": 32000,
      "rating": 4,
      "imageFile": "persimmon-candle.png",
      "imageUrl": "assets/images/products/persimmon-candle.png",
      "sourceImage": "Rectangle 31-10.png",
      "description": "Nến thơm hình quả hồng có thiết kế đáng yêu, màu sắc nổi bật và hương thơm dịu nhẹ, phù hợp để làm mới góc phòng.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, bàn làm việc; Tạo góc sống ảo; Làm quà tặng tinh tế"
    },
    {
      "legacyCategoryId": 3,
      "categorySlug": "tranh-decor",
      "slug": "green-leaf-frame",
      "name": "Tranh khung trắng vẽ lá trầu bà nam mỹ màu xanh rêu tối giản phong cách",
      "price": 50000,
      "rating": 4,
      "imageFile": "green-leaf-frame.png",
      "imageUrl": "assets/images/products/green-leaf-frame.png",
      "sourceImage": "Rectangle 33.png",
      "description": "Tranh khung trắng vẽ lá trầu bà Nam Mỹ mang sắc xanh rêu trầm ấm, tạo cảm giác thiên nhiên, bình yên và hiện đại.",
      "suitableFor": "Treo tường phòng khách, phòng ngủ; Decor quán cà phê, homestay, spa; Làm quà tặng sinh nhật"
    },
    {
      "legacyCategoryId": 7,
      "categorySlug": "coc-va-phu-kien",
      "slug": "chubby-cup",
      "name": "Cốc chiếc mỡ núng nính đáng yêu",
      "price": 118000,
      "rating": 4,
      "imageFile": "chubby-cup.png",
      "imageUrl": "assets/images/products/chubby-cup.png",
      "sourceImage": "glass2.png",
      "description": "Cốc chiếc mỡ núng nính có tạo hình bụng tròn ngộ nghĩnh, mang lại cảm giác vui vẻ và đáng yêu cho mỗi ngày.",
      "suitableFor": "Thưởng thức sữa, trà, cà phê; Làm đồ decor đáng yêu; Làm quà tặng vui nhộn"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "cafe-chill-set",
      "name": "Set cà phê chill tại nhà",
      "price": 558000,
      "rating": 4,
      "imageFile": "cafe-chill-set.png",
      "imageUrl": "assets/images/products/cafe-chill-set.png",
      "sourceImage": "set2.png",
      "description": "Set cà phê chill tại nhà giúp biến góc nhỏ thành không gian thư giãn nghệ thuật với ly sứ, nến thơm, loa mini và phụ kiện decor.",
      "suitableFor": "Tạo góc ban công, phòng khách, phòng ăn; Decor pantry, studio, homestay; Làm quà tặng đặc biệt"
    },
    {
      "legacyCategoryId": 10,
      "categorySlug": "gia-do",
      "slug": "book-stand",
      "name": "Giá đỡ sách gỗ tiện ích",
      "price": 55000,
      "rating": 4,
      "imageFile": "book-stand.png",
      "imageUrl": "assets/images/products/book-stand.png",
      "sourceImage": "Rectangle 31-17.png",
      "description": "Giá đỡ sách gỗ tiện ích có thiết kế mộc mạc, hỗ trợ đọc sách, truyện tranh, máy tính bảng hoặc điện thoại.",
      "suitableFor": "Đỡ sách, truyện tranh, máy tính bảng; Làm giá trưng bày; Làm quà tặng cho học sinh, sinh viên"
    },
    {
      "legacyCategoryId": 4,
      "categorySlug": "den-trang-tri",
      "slug": "flan-lamp",
      "name": "Đèn Bàn Mini Hình Bánh Flan Giả Cổ Phong Cách Vintage Trang Trí",
      "price": 69000,
      "rating": 4,
      "imageFile": "flan-lamp.png",
      "imageUrl": "assets/images/products/flan-lamp.png",
      "sourceImage": "Rectangle 31-18.png",
      "description": "Đèn bàn mini hình bánh flan giả cổ tạo ánh sáng ấm áp, mang phong cách vintage ngọt ngào và độc đáo.",
      "suitableFor": "Trang trí phòng ngủ, bàn làm việc, quán cà phê vintage; Tạo góc check-in retro; Làm quà tặng decor"
    },
    {
      "legacyCategoryId": 8,
      "categorySlug": "binh-hoa",
      "slug": "pastel-vase",
      "name": "Bình hoa màu pastel hồng trắng dễ thương",
      "price": 102000,
      "rating": 4,
      "imageFile": "pastel-vase.png",
      "imageUrl": "assets/images/products/pastel-vase.png",
      "sourceImage": "vase3.png",
      "description": "Bình hoa pastel hồng trắng có thiết kế mềm mại, thanh lịch, phù hợp cắm các cành hoa nhỏ để tạo cảm giác nhẹ nhàng.",
      "suitableFor": "Trang trí bàn học, bàn làm việc, kệ sách; Decor không gian Hàn Quốc; Làm quà tặng sinh nhật"
    },
    {
      "legacyCategoryId": 9,
      "categorySlug": "chau-cay",
      "slug": "mini-plant-pot",
      "name": "Chậu cây mini phong cách dễ thương trồng cây cảnh",
      "price": 56000,
      "rating": 4,
      "imageFile": "mini-plant-pot.png",
      "imageUrl": "assets/images/products/mini-plant-pot.png",
      "sourceImage": "pot1.png",
      "description": "Chậu cây mini hình thú dễ thương, phù hợp trồng sen đá, xương rồng hoặc cây không khí, giúp góc nhỏ thêm sinh động.",
      "suitableFor": "Trang trí bàn học, bàn làm việc, bệ cửa sổ; Decor phòng ngủ, ban công; Làm quà lưu niệm"
    },
    {
      "legacyCategoryId": 3,
      "categorySlug": "tranh-decor",
      "slug": "abstract-orange-plant",
      "name": "Tranh treo tường trừu tượng hình chậu cây cam khối hình học",
      "price": 50000,
      "rating": 4,
      "imageFile": "abstract-orange-plant.png",
      "imageUrl": "assets/images/products/abstract-orange-plant.png",
      "sourceImage": "Rectangle 31-16.png",
      "description": "Tranh treo tường hình chậu cây cam khối hình học có phong cách hiện đại, màu cam ấm áp và bố cục nghệ thuật.",
      "suitableFor": "Treo phòng khách, phòng ăn, bàn làm việc; Decor quán cà phê, homestay; Làm quà tặng tân gia"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "combo-reading-corner",
      "name": "Combo Góc Đọc Sách",
      "price": 319000,
      "rating": 4,
      "imageFile": "combo-reading-corner.png",
      "imageUrl": "assets/images/products/combo-reading-corner.png",
      "sourceImage": "set4.png",
      "description": "Combo Góc Đọc Sách mang đến không gian thư giãn ấm áp với sự kết hợp của kệ sách, ghế đọc, đồng hồ, nến thơm, tượng decor và các vật phẩm trang trí nhẹ nhàng. Bộ sản phẩm phù hợp để tạo một góc đọc sách riêng tư, yên tĩnh và đầy cảm hứng.",
      "suitableFor": "Setup góc đọc sách, góc thiền, tab đầu giường hoặc cạnh cửa sổ; Decor homestay, studio, phòng ngủ hoặc không gian thư giãn; Làm quà tặng sinh nhật, quà tặng quan tâm cho người thân và bạn bè"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "combo-sleep-corner",
      "name": "Combo Góc ngủ ngon",
      "price": 367000,
      "rating": 4,
      "imageFile": "combo-sleep-corner.png",
      "imageUrl": "assets/images/products/combo-sleep-corner.png",
      "sourceImage": "set5.png",
      "description": "Combo Góc ngủ ngon giúp tạo nên không gian nghỉ ngơi ấm áp với ánh sáng vàng dịu, đồng hồ gỗ, khay nến và các vật phẩm decor mang cảm giác thư thái. Bộ sản phẩm phù hợp để làm mới tab đầu giường hoặc góc nhỏ trong phòng ngủ.",
      "suitableFor": "Trang trí phòng ngủ, tab đầu giường, góc thư giãn cá nhân; Tạo không gian ấm áp, dễ chịu trước khi ngủ; Làm quà tặng tinh tế cho người thân và bạn bè"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "combo-healing-corner",
      "name": "Combo Chill Chữa Lành",
      "price": 425000,
      "rating": 4,
      "imageFile": "combo-healing-corner.png",
      "imageUrl": "assets/images/products/combo-healing-corner.png",
      "sourceImage": "set6.png",
      "description": "Combo Chill Chữa Lành là set decor mang phong cách nhẹ nhàng, kết hợp ly sứ, tranh hoa, phụ kiện thơm và các chi tiết trang trí giúp không gian trở nên bình yên hơn. Sản phẩm phù hợp cho những ai yêu thích cảm giác thư giãn, mềm mại và gần gũi.",
      "suitableFor": "Decor phòng ngủ, bàn trang điểm, góc cửa sổ hoặc phòng tắm; Bày trí không gian spa, yoga, homestay hoặc phòng trà; Làm quà tặng chăm sóc tinh thần cho bạn bè, đồng nghiệp và người thân"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "combo-entertainment-corner",
      "name": "Combo Góc giải trí",
      "price": 455000,
      "rating": 4,
      "imageFile": "combo-entertainment-corner.png",
      "imageUrl": "assets/images/products/combo-entertainment-corner.png",
      "sourceImage": "set7.png",
      "description": "Combo Góc giải trí mang đến một không gian sống động và hiện đại với loa bluetooth mini, nến thơm, tranh decor và các phụ kiện trang trí nổi bật. Bộ sản phẩm phù hợp để biến góc xem phim, nghe nhạc hoặc phòng khách thành điểm nhấn đầy cảm hứng.",
      "suitableFor": "Nâng cấp không gian phòng khách, kệ tivi hoặc bàn trà; Decor phòng giải trí, phòng game hoặc góc nghe nhạc; Làm quà tặng công nghệ và phong cách cho bạn bè, người thân"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "combo-art-corner",
      "name": "Combo Góc nghệ thuật",
      "price": 366000,
      "rating": 4,
      "imageFile": "combo-art-corner.png",
      "imageUrl": "assets/images/products/combo-art-corner.png",
      "sourceImage": "set8.png",
      "description": "Combo Góc nghệ thuật là sự kết hợp hài hòa giữa tranh decor, tượng trang trí, bình hoa, nến thơm và các phụ kiện mang hơi hướng tối giản. Bộ sản phẩm giúp tạo điểm nhấn nghệ thuật cho bàn làm việc, kệ sách hoặc góc sáng tạo.",
      "suitableFor": "Bày trí kệ tivi, bàn làm việc, kệ sách hoặc console lối ra vào; Decor studio, văn phòng sáng tạo, phòng trà hoặc quán cafe; Làm quà tặng nghệ thuật cho người yêu thích decor và sự tối giản"
    },
    {
      "legacyCategoryId": 2,
      "categorySlug": "nen-thom",
      "slug": "ocean-shell-candle",
      "name": "Nến thơm hình vỏ ốc biển màu xanh dương chữa lành",
      "price": 59000,
      "rating": 4,
      "imageFile": "ocean-shell-candle.png",
      "imageUrl": "assets/images/products/ocean-shell-candle.png",
      "sourceImage": "Rectangle 31-23.png",
      "description": "Nến thơm hình vỏ ốc biển màu xanh dương mang cảm giác đại dương mát lành vào không gian sống. Thiết kế vỏ ốc độc đáo kết hợp sắc xanh dịu mắt và ánh nến lung linh giúp góc phòng trở nên thư giãn, nghệ thuật và chữa lành hơn.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, bàn làm việc; Tạo góc sống ảo, góc chill tại nhà; Làm quà tặng tinh tế cho bạn bè và người thân"
    },
    {
      "legacyCategoryId": 3,
      "categorySlug": "tranh-decor",
      "slug": "diy-3d-plaster-art",
      "name": "Tranh thạch cao nổi 3D tự tô màu",
      "price": 46000,
      "rating": 4,
      "imageFile": "diy-3d-plaster-art.png",
      "imageUrl": "assets/images/products/diy-3d-plaster-art.png",
      "sourceImage": "Rectangle 31-24.png",
      "description": "Tranh thạch cao nổi 3D tự tô màu là sản phẩm decor sáng tạo cho phép người dùng tự phối màu và hoàn thiện tác phẩm theo sở thích cá nhân. Bề mặt hoa nổi sinh động giúp sản phẩm vừa là đồ trang trí vừa là hoạt động thư giãn thú vị.",
      "suitableFor": "Đặt decor trên bàn làm việc, bàn học, kệ sách hoặc tủ trang trí; Hoạt động giải trí, thư giãn, xả stress vào cuối tuần; Làm quà tặng handmade độc đáo cho người yêu thích hội họa và decor"
    },
    {
      "legacyCategoryId": 7,
      "categorySlug": "coc-va-phu-kien",
      "slug": "mini-bluetooth-speaker",
      "name": "Loa bluetooth mini",
      "price": 153000,
      "rating": 4,
      "imageFile": "mini-bluetooth-speaker.png",
      "imageUrl": "assets/images/products/mini-bluetooth-speaker.png",
      "sourceImage": "Rectangle 31-25.png",
      "description": "Loa bluetooth mini sở hữu thiết kế nhỏ gọn, đáng yêu với hiệu ứng đèn LED đổi màu nổi bật. Sản phẩm phù hợp để nghe nhạc, hát karaoke nhẹ nhàng và đồng thời làm phụ kiện decor hiện đại cho góc làm việc hoặc phòng ngủ.",
      "suitableFor": "Hát karaoke giải trí cùng gia đình, bạn bè; Decor bàn làm việc, kệ sách hoặc góc chill; Làm quà tặng công nghệ cho người yêu âm nhạc"
    },
    {
      "legacyCategoryId": 2,
      "categorySlug": "nen-thom",
      "slug": "essential-oil-diffuser",
      "name": "Khuếch tán tinh dầu",
      "price": 309000,
      "rating": 4,
      "imageFile": "essential-oil-diffuser.png",
      "imageUrl": "assets/images/products/essential-oil-diffuser.png",
      "sourceImage": "Rectangle 31-26.png",
      "description": "Máy khuếch tán tinh dầu giúp lan tỏa hương thơm dịu nhẹ, tạo bầu không khí thư thái và ấm cúng. Thiết kế hiện đại kết hợp ánh đèn vàng giúp sản phẩm vừa có công năng thư giãn vừa là phụ kiện decor cuốn hút.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, bàn làm việc; Tạo góc thư giãn lãng mạn tại nhà; Làm quà tặng tân gia, sinh nhật cho bạn bè và người thân"
    },
    {
      "legacyCategoryId": 10,
      "categorySlug": "gia-do",
      "slug": "laptop-stand",
      "name": "Giá đỡ laptop tiện ích, dễ dùng",
      "price": 110000,
      "rating": 4,
      "imageFile": "laptop-stand.png",
      "imageUrl": "assets/images/products/laptop-stand.png",
      "sourceImage": "Rectangle 31-21.png",
      "description": "Giá đỡ laptop tiện ích có thiết kế kim loại chắc chắn với nhiều nấc điều chỉnh độ cao linh hoạt. Sản phẩm giúp nâng máy vừa tầm mắt, cải thiện tư thế ngồi, hỗ trợ tản nhiệt và giúp góc làm việc trở nên gọn gàng hơn.",
      "suitableFor": "Đỡ laptop, máy tính bảng khi làm việc hoặc học tập; Tối ưu tư thế ngồi và hỗ trợ tản nhiệt cho thiết bị; Làm quà tặng thiết thực cho dân văn phòng, học sinh, sinh viên và freelancer"
    },
    {
      "legacyCategoryId": 4,
      "categorySlug": "den-trang-tri",
      "slug": "crystal-wave-lamp",
      "name": "Đèn ngủ pha lê hình trụ vân sóng nước tạo hiệu ứng ánh sáng sang trọng",
      "price": 79000,
      "rating": 4,
      "imageFile": "crystal-wave-lamp.png",
      "imageUrl": "assets/images/products/crystal-wave-lamp.png",
      "sourceImage": "Rectangle 31-22.png",
      "description": "Đèn ngủ pha lê hình trụ vân sóng nước tạo hiệu ứng phản chiếu ánh sáng lung linh lên tường và không gian xung quanh. Ánh sáng vàng ấm giúp căn phòng trở nên thư thái, sang trọng và có chiều sâu hơn.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, tab đầu giường; Thiết kế góc chill, góc sống ảo lãng mạn tại nhà; Làm quà tặng tân gia, sinh nhật tinh tế"
    },
    {
      "legacyCategoryId": 8,
      "categorySlug": "binh-hoa",
      "slug": "korean-ceramic-vase",
      "name": "Bình hoa gốm sứ thắt eo đính ruy băng hồng phong cách Hàn Quốc decor",
      "price": 105000,
      "rating": 4,
      "imageFile": "korean-ceramic-vase.png",
      "imageUrl": "assets/images/products/korean-ceramic-vase.png",
      "sourceImage": "vase4.png",
      "description": "Bình hoa gốm sứ thắt eo đính ruy băng hồng mang phong cách Hàn Quốc nhẹ nhàng và thanh lịch. Thiết kế độc đáo cùng tông màu kem ấm giúp sản phẩm dễ phối với hoa khô, hoa lụa hoặc các góc decor nhỏ.",
      "suitableFor": "Trang trí bàn học, bàn làm việc, bàn trà phòng khách hoặc kệ tủ; Decor phòng ngủ, tiệm cafe, studio chụp ảnh theo phong cách nhẹ nhàng; Làm quà tặng sinh nhật, quà tân gia xinh xắn"
    },
    {
      "legacyCategoryId": 1,
      "categorySlug": "combo-decor",
      "slug": "healing-relax-set",
      "name": "Set Chữa Lành relax - healing",
      "price": 468000,
      "rating": 4,
      "imageFile": "healing-relax-set.png",
      "imageUrl": "assets/images/products/healing-relax-set.png",
      "sourceImage": "set3.png",
      "description": "Set Chữa Lành relax - healing là combo decor kết hợp máy khuếch tán tinh dầu, đèn ngủ, nến thơm, tranh thạch cao và các phụ kiện mang cảm giác bình yên. Bộ sản phẩm giúp biến góc nhỏ thành nơi thư giãn, tái tạo năng lượng sau những giờ học tập và làm việc căng thẳng.",
      "suitableFor": "Decor phòng ngủ, bàn trang điểm, góc đọc sách hoặc kệ phòng tắm; Bày trí phòng trà, phòng thiền, spa hoặc homestay phong cách mộc mạc; Làm quà tặng chữa lành cho người thân, bạn bè và đồng nghiệp"
    },
    {
      "legacyCategoryId": 5,
      "categorySlug": "tuong-trang-tri",
      "slug": "thinking-statue",
      "name": "Tượng decor \"Bức Tượng Suy Nghĩ\"",
      "price": 36000,
      "rating": 4,
      "imageFile": "thinking-statue.png",
      "imageUrl": "assets/images/products/thinking-statue.png",
      "sourceImage": "Rectangle 31-3.png",
      "description": "Tượng decor \"Bức Tượng Suy Nghĩ\" mang phong cách tối giản với tạo hình người ngồi suy tư, phù hợp để tạo chiều sâu nghệ thuật cho không gian sống. Tông màu trắng trang nhã giúp sản phẩm dễ phối với nhiều phong cách nội thất từ hiện đại đến tối giản.",
      "suitableFor": "Trang trí phòng khách, phòng làm việc, kệ sách hoặc tab đầu giường; Tạo điểm nhấn cho góc chụp ảnh, studio hoặc không gian decor tối giản; Làm quà tặng tân gia, quà tặng đồng nghiệp hoặc bạn bè yêu thích nghệ thuật"
    },
    {
      "legacyCategoryId": 3,
      "categorySlug": "tranh-decor",
      "slug": "fleur-de-jardin-canvas",
      "name": "Tranh treo tường canvas fleur de jardin phong cách thực vật học pháp cổ điển",
      "price": 50000,
      "rating": 4,
      "imageFile": "fleur-de-jardin-canvas.png",
      "imageUrl": "assets/images/products/fleur-de-jardin-canvas.png",
      "sourceImage": "Rectangle 32.png",
      "description": "Tranh treo tường canvas fleur de jardin mang phong cách thực vật học Pháp cổ điển, nổi bật với họa tiết hoa lá tinh tế trên nền màu nhẹ nhàng. Sản phẩm giúp không gian trở nên lãng mạn, cổ điển và có chiều sâu nghệ thuật hơn.",
      "suitableFor": "Treo tường phòng khách, phòng ngủ hoặc đặt trên bàn làm việc, kệ sách; Decor quán cà phê, studio, homestay theo phong cách Vintage, Retro hoặc French Country; Làm quà tặng tân gia, quà sinh nhật cho người yêu thích hội họa và thiên nhiên"
    },
    {
      "legacyCategoryId": 4,
      "categorySlug": "den-trang-tri",
      "slug": "sea-urchin-lamp",
      "name": "Đèn ngủ vỏ nhím biển tự nhiên để bàn decor dễ thương",
      "price": 109000,
      "rating": 4,
      "imageFile": "sea-urchin-lamp.png",
      "imageUrl": "assets/images/products/sea-urchin-lamp.png",
      "sourceImage": "Rectangle 31-7.png",
      "description": "Đèn ngủ vỏ nhím biển tự nhiên mang hơi thở bình yên của đại dương vào không gian sống. Ánh sáng vàng ấm kết hợp cùng chất liệu vỏ nhím biển tạo cảm giác thư giãn, nhẹ nhàng và độc đáo cho căn phòng.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, bàn làm việc hoặc tab đầu giường; Tạo góc sống ảo, góc thư giãn nhẹ nhàng tại nhà; Làm quà tặng tân gia, sinh nhật độc lạ và tinh tế cho bạn bè, người thân"
    },
    {
      "legacyCategoryId": 5,
      "categorySlug": "tuong-trang-tri",
      "slug": "wind-soul-statue",
      "name": "Tượng decor nghệ thuật \"Thả hồn theo gió\"",
      "price": 36000,
      "rating": 4,
      "imageFile": "wind-soul-statue.png",
      "imageUrl": "assets/images/products/wind-soul-statue.png",
      "sourceImage": "Rectangle 31-13.png",
      "description": "Tượng decor nghệ thuật \"Thả hồn theo gió\" có thiết kế trừu tượng tối giản, mô phỏng dáng người ngồi thư thái với những đường nét mềm mại. Sản phẩm mang đến cảm giác bình yên, phóng khoáng và nghệ thuật cho góc nhỏ trong nhà.",
      "suitableFor": "Trang trí phòng khách, phòng làm việc, kệ sách, tab đầu giường hoặc tủ tivi; Làm điểm nhấn decor cho góc chụp ảnh, studio hoặc không gian phong cách Minimalism; Làm quà tặng tân gia, quà tặng bạn bè, đồng nghiệp tinh tế và ý nghĩa"
    },
    {
      "legacyCategoryId": 2,
      "categorySlug": "nen-thom",
      "slug": "butter-cookie-candle-set",
      "name": "Combo hộp 4 nến thơm hình bánh quy bơ",
      "price": 65000,
      "rating": 4,
      "imageFile": "butter-cookie-candle-set.png",
      "imageUrl": "assets/images/products/butter-cookie-candle-set.png",
      "sourceImage": "Rectangle 31-15.png",
      "description": "Combo hộp 4 nến thơm hình bánh quy bơ có thiết kế đáng yêu, mô phỏng những chiếc bánh quy nhỏ xinh với nhiều kiểu dáng khác nhau. Sản phẩm vừa tạo hương thơm dịu nhẹ vừa là món phụ kiện decor ngọt ngào cho bàn học, kệ sách hoặc góc chill.",
      "suitableFor": "Trang trí phòng khách, phòng ngủ, bàn làm việc; Tạo góc sống ảo, góc chill tại nhà; Làm quà tặng tinh tế cho bạn bè và người thân"
    }
  ]
};

module.exports = productData;
